version: "3.8"
services:
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: ["5000:5000"]
    depends_on:
      - mongo

  frontend:
    build:
      context: ./src # ← points at your React app
      dockerfile: Dockerfile
    ports: ["5173:5173"]
    depends_on:
      - backend

volumes:
  mongo-data:
