version: "3.8"
services:
  frontend:
    # reuse the build context & Dockerfile from your top-level
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    volumes:
      - ..:/workspaces/redecorai:cached
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
